#!/bin/bash

NOTEFILE='savefile.txt'
echo `date` >> $NOTEFILE

# If run with no commands saves the last command entered
if [[ -z $1 ]]; then
    history -a
    LASTCMD=$(tail -1 ~/.bash_history)
    echo "$LASTCMD" >> $NOTEFILE

elif [[ $1 == "-e" ]]; then
    echo "${@:2:99}" >> $NOTEFILE 
    "${@:2:99}" |& tee -a $NOTEFILE

# Enter interactive bash mode to save everything
elif [[ $1 == "-i" ]]; then
    $2 |& tee -a $3

elif [[ $1 == "-p" ]];then
    echo "Parsing..."
    ./bashparser.py $2 $3

elif [[ $1 == "me" ]]; then
	echo "You can do anything!! :)"
	echo "YOU CAN DO ANYTHING!!"
else
    echo $@ >> $NOTEFILE
fi
